sudo: false
addons:
    apt:
        sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
        packages:
            - python3.5
            - python3.5-dev
            - python-pip
            - python-virtualenv
            - gcc-4.9
            - g++-4.9
            # Needed for ARM gcc
            - lib32bz2-1.0
            - lib32ncurses5
            - lib32z1

language: cpp

matrix:
    include:
        - compiler: clang
          env: BUILD_TYPE="tests"
        - compiler: gcc
          env: BUILD_TYPE="tests"
        - compiler: clang
          env: BUILD_TYPE="client-tests"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="motor-board-v1"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="rc-board-v1"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="olimex-e407"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="can-io-board"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="nucleo-board-stm32f103rb"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="nucleo-board-stm32f334r8"
        - compiler: gcc
          env: BUILD_TYPE="build" PLATFORM="uwb-beacon"

before_install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

install:
    - ci/install.sh

script:
    - ci/build.sh


