
#
# Bootloader response datagram error codes
# as defined error.h
#

class Error:
    SUCCESS = 1
    UNSPECIFIED_ERROR = 0

    CORRUPT_DATAGRAM = 2
    DATAGRAM_TIMEOUT = 6
    INVALID_COMMAND = 3
    COMMAND_NOT_FOUND = 4
    INVALID_COMMAND_SET_VERSION = 5

    FLASH_ERASE_ERROR_BEFORE_APP = 10
    FLASH_ERASE_ERROR_AFTER_APP = 11
    FLASH_ERASE_ERROR_DEVICE_CLASS_MISMATCH = 12

    FLASH_WRITE_ERROR_BEFORE_APP = 20
    FLASH_WRITE_ERROR_AFTER_APP = 21
    FLASH_WRITE_ERROR_DEVICE_CLASS_MISMATCH = 22
    FLASH_WRITE_ERROR_UNKNOWN_SIZE = 23
    FLASH_WRITE_ERROR_NOT_ERASED = 24

    CRC_ERROR_ADDRESS_UNSPECIFIED = 30
    CRC_ERROR_LENGTH_UNSPECIFIED = 31
    CRC_ERROR_ILLEGAL_ADDRESS = 32
